package net.tiew.operationWild.entity.client.animation;

import net.minecraft.client.animation.AnimationChannel;
import net.minecraft.client.animation.AnimationDefinition;
import net.minecraft.client.animation.Keyframe;
import net.minecraft.client.animation.KeyframeAnimations;

public class MandrillAnimations {


	public static final AnimationDefinition MISC_IDLE = AnimationDefinition.Builder.withLength(3.55619f).looping()
			.addAnimation("body",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(-5f, 2.49f, -0.22f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.77809f, KeyframeAnimations.degreeVec(2.5f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.55619f, KeyframeAnimations.degreeVec(-5f, 2.49f, -0.22f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("left_leg",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0f, KeyframeAnimations.posVec(1f, 0f, -1f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("left_leg",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(-25f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("left_leg2",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(25f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("right_leg",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("right_leg",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(-25f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("right_leg2",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(25f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("left_arm",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0f, KeyframeAnimations.posVec(0f, 1f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("left_arm",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, -15f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("right_arm",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0f, KeyframeAnimations.posVec(0f, 1f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("right_arm",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 15f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("head",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0.64011f, KeyframeAnimations.degreeVec(0f, -5f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2.41821f, KeyframeAnimations.degreeVec(5.02f, 4.98f, 0.44f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.55619f, KeyframeAnimations.degreeVec(0f, -5f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("left_eyeBall",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.63585f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.77809f, KeyframeAnimations.posVec(0f, -1f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.92034f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2.06259f, KeyframeAnimations.posVec(0f, -1f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2.20484f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("right_eyeBall",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.63585f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.77809f, KeyframeAnimations.posVec(0f, -1f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.92034f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2.06259f, KeyframeAnimations.posVec(0f, -1f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2.20484f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("tail",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(12.5f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.77809f, KeyframeAnimations.degreeVec(37.5f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.55619f, KeyframeAnimations.degreeVec(12.5f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("ALL",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0f, KeyframeAnimations.posVec(0f, -1f, 0f),
									AnimationChannel.Interpolations.CATMULLROM))).build();
	public static final AnimationDefinition MOVE_WALK = AnimationDefinition.Builder.withLength(1.4f).looping()
			.addAnimation("body",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.4f, KeyframeAnimations.posVec(0f, -1f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.73333f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.06667f, KeyframeAnimations.posVec(0f, -1f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.4f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("body",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(2.51f, 5.1f, -2.28f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.4f, KeyframeAnimations.degreeVec(-0.69f, 6.16f, -7.19f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.73333f, KeyframeAnimations.degreeVec(2.51f, -5.1f, 2.28f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.06667f, KeyframeAnimations.degreeVec(-0.68f, -6.14f, 7.08f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.4f, KeyframeAnimations.degreeVec(2.51f, 5.1f, -2.28f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("left_leg",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.4f, KeyframeAnimations.posVec(0f, 1.5f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.06667f, KeyframeAnimations.posVec(0f, 3f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.4f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("left_leg",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(-38.3f, -21.04f, 1.54f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.6f, KeyframeAnimations.degreeVec(40.68f, -11.51f, -6.91f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.4f, KeyframeAnimations.degreeVec(-38.3f, -21.04f, 1.54f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("left_leg2",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0.2f, KeyframeAnimations.degreeVec(20f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.86667f, KeyframeAnimations.degreeVec(52.5f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.4f, KeyframeAnimations.degreeVec(20f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("right_leg",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.33333f, KeyframeAnimations.posVec(0f, 2f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.6f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.4f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("right_leg",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(40.68f, 11.51f, 6.91f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.6f, KeyframeAnimations.degreeVec(-38.3f, 21.04f, -1.54f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.4f, KeyframeAnimations.degreeVec(40.68f, 11.51f, 6.91f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("right_leg2",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0.2f, KeyframeAnimations.degreeVec(52.5f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.86667f, KeyframeAnimations.degreeVec(20f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.4f, KeyframeAnimations.degreeVec(52.5f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("left_arm",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0f, KeyframeAnimations.posVec(0f, 2f, 1f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.4f, KeyframeAnimations.posVec(0.55f, 4f, 0.45f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.73333f, KeyframeAnimations.posVec(1f, 1f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.4f, KeyframeAnimations.posVec(0f, 2f, 1f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("left_arm",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(30.07f, -9.32f, -6.18f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.73333f, KeyframeAnimations.degreeVec(-62.12f, -13.49f, 8.6f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.4f, KeyframeAnimations.degreeVec(30.07f, -9.32f, -6.18f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("right_arm",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0f, KeyframeAnimations.posVec(-1f, 1f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.73333f, KeyframeAnimations.posVec(0f, 2f, 1f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.06667f, KeyframeAnimations.posVec(-0.5f, 4f, 0.5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.4f, KeyframeAnimations.posVec(-1f, 1f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("right_arm",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(-62.12f, 13.49f, -8.6f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.73333f, KeyframeAnimations.degreeVec(30.07f, 9.32f, 6.18f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.4f, KeyframeAnimations.degreeVec(-62.12f, 13.49f, -8.6f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("head",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(-4.67f, 7.49f, -4.98f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.66667f, KeyframeAnimations.degreeVec(5.33f, -7.49f, 4.98f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.4f, KeyframeAnimations.degreeVec(-4.67f, 7.49f, -4.98f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("left_eyeBall",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.6f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.8f, KeyframeAnimations.posVec(0f, -0.5f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.2f, KeyframeAnimations.posVec(0f, -0.5f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.4f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("right_eyeBall",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.6f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.8f, KeyframeAnimations.posVec(0f, -0.5f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.2f, KeyframeAnimations.posVec(0f, -0.5f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.4f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("tail",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(10f, 32.5f, 12.5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.4f, KeyframeAnimations.degreeVec(-2.5f, 32.5f, 12.5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.73333f, KeyframeAnimations.degreeVec(10f, -32.5f, -12.5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.06667f, KeyframeAnimations.degreeVec(32.5f, -32.5f, -12.5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.4f, KeyframeAnimations.degreeVec(10f, 32.5f, 12.5f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("ALL",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0f, KeyframeAnimations.posVec(0f, -2f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.4f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.73333f, KeyframeAnimations.posVec(0f, -2f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.06667f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.4f, KeyframeAnimations.posVec(0f, -2f, 0f),
									AnimationChannel.Interpolations.CATMULLROM))).build();

}
